/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import da.ProductDA;
import da.PromotionDA;
import da.PromotionProductDA;
import domain.Product;
import domain.Promotion;
import domain.Promotionproduct;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author AL
 */
public class MonthlyPromotionItem extends javax.swing.JFrame {
private String host = "jdbc:derby://localhost:1527/FlowerDB";
    private String user = "nbuser";
    private String password = "nbuser";
    private Connection conn;
    private PreparedStatement stmt;
    private Statement st;
    private String seletedP = null;
    /**
     * Creates new form MonthlyPromotionItem
     */
    public MonthlyPromotionItem() {
        initComponents();
        //Promotion Name
        addItemToJCBPN();
        
       
        
        //Product
        addItemToJCBNPI();

    }
    
    public void addItemToJCBPN(){
        PromotionDA pDA = new PromotionDA();
        Promotion p = new Promotion();
        List<Promotion> pList=new ArrayList<Promotion>();
        pList=pDA.getAllRecord();
        for(Promotion pp : pList  ){
            jcbPN.addItem(pp.getPromotionname());
        }
    }
    
    public void addItemToJCBNPI(){
         String promotionName  =jcbPN.getSelectedItem().toString();
                PromotionProductDA ppDA=new PromotionProductDA();
        Promotionproduct pp = new Promotionproduct();
        List<Promotionproduct> ppList=new ArrayList< Promotionproduct>();
        ppList=ppDA.getAllSelectedRecord(promotionName);
        ProductDA pDA1 = new ProductDA();
        Product p1 = new Product();
        List<Product> pList1=new ArrayList<Product>();
        pList1=pDA1.getAllRecord();
        for(Product prod : pList1  ){
             jcbNPI.addItem(prod.getProductname());
            for(Promotionproduct pProd : ppList  ){
                if(pProd.getProductname().equals(prod.getProductname())) {        
                jcbNPI.removeItem(prod.getProductname());
                break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FioreFlowershopSystemPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("FioreFlowershopSystemPU").createEntityManager();
        promotionQuery = java.beans.Beans.isDesignTime() ? null : FioreFlowershopSystemPUEntityManager.createQuery("SELECT p FROM Promotion p");
        promotionList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : promotionQuery.getResultList();
        promotionQuery1 = java.beans.Beans.isDesignTime() ? null : FioreFlowershopSystemPUEntityManager.createQuery("SELECT p FROM Promotion p");
        promotionList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : promotionQuery1.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfDP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jcbPN = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jcbNPI = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        jLabel5.setText("Fiore Flowershop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setText("Add Monthly Promotion");

        jLabel2.setText("Promotion Name:");

        jLabel7.setText("Discounted price:");

        jtfDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDPActionPerformed(evt);
            }
        });

        jButton1.setText("Add Promotion Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcbPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPNActionPerformed(evt);
            }
        });

        jLabel1.setText("New Promotion Item:");

        jcbNPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNPIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbNPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfDP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbNPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public String createPromotionProductID(){
         PromotionProductDA ppDA = new PromotionProductDA();
        List<Promotionproduct> pList=new ArrayList<Promotionproduct>();
        String ppID = null;
        char idCore;
         pList=ppDA.getAllRecord();
        for (Promotionproduct a: pList){
            ppID=a.getPromotiomitemid();
        }
        if(ppID==null){
            ppID="P000";
        }
        idCore=ppID.charAt(0);
        int hun=Character.getNumericValue(ppID.charAt(1));
        int ten=Character.getNumericValue(ppID.charAt(2));
        int one=Character.getNumericValue(ppID.charAt(3));
        one++;
        if(one==10){
            ten++;
            one=0;
        }
        if(ten==10){
            hun++;
            ten=0;
        }
        return idCore+Integer.toString(hun)+Integer.toString(ten)+Integer.toString(one);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //create pp ID       
        if(jtfDP.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the price!");
        }else{
        Promotionproduct pp = new Promotionproduct();
        PromotionProductDA ppDA= new PromotionProductDA();
        pp.setPromotiomitemid(createPromotionProductID());
        pp.setPromotionname(jcbPN.getSelectedItem().toString());
        pp.setProductname(jcbNPI.getSelectedItem().toString());
        pp.setDiscountprice(Double.parseDouble(jtfDP.getText()));
        ppDA.addRecord(pp);
        JOptionPane.showMessageDialog(null,"Add Successfully!!");
        jcbNPI.removeAllItems();
        addItemToJCBNPI();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPNActionPerformed
        // TODO add your handling code here:   
        jcbNPI.removeAllItems();
        addItemToJCBNPI();
        
    }//GEN-LAST:event_jcbPNActionPerformed

    private void jcbNPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbNPIActionPerformed

    private void jtfDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlyPromotionItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlyPromotionItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlyPromotionItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlyPromotionItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlyPromotionItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager FioreFlowershopSystemPUEntityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbNPI;
    private javax.swing.JComboBox<String> jcbPN;
    private javax.swing.JTextField jtfDP;
    private java.util.List<Domain.Promotion> promotionList;
    private java.util.List<Domain.Promotion> promotionList1;
    private javax.persistence.Query promotionQuery;
    private javax.persistence.Query promotionQuery1;
    // End of variables declaration//GEN-END:variables
}
